theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: hero-end
  posts:
    index:
      layout: grid
  debug:
     productionUrl: "https://podcast.culturesnumeriques.net"
