[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/fr/mentions-legales/"
to = "/mentions-legales/"

[[redirects]]
from = "/lives/2022/12/07/douglas-stanley/"
to = "/lives/2023-02-07-douglas-stanley/"

[[redirects]]
from = "/lives/2022/09/12/antoine-menard/"
to = "/lives/2022-09-12-antoine-menard/"

[[redirects]]
from = "/actualites/a-venir/"
to = "/lives/a-venir/"

[[redirects]]
from = "/lives/2022/11/04/morgane-chevalier-adrien-payet/"
to = "/lives/2022-11-04-morgane-chevalier-adrien-payet/"

[[redirects]]
from = "/fr/plan-du-site/"
to = "/plan-du-site/"

[[redirects]]
from = "/lives/2022-12-07-douglas-stanley/"
to = "/lives/2023-02-07-douglas-stanley/"

[[redirects]]
from = "/fr/politique-de-confidentialite/"
to = "/politique-de-confidentialite/"

[[redirects]]
from = "/fr/actualites/"
to = "/lives/"

[[redirects]]
from = "/lives/2022-12-11-anaelle-martin/"
to = "/lives/2023-02-06-anaelle-martin/"

[[redirects]]
from = "/fr/accessibilite/"
to = "/accessibilite/"

[[redirects]]
from = "/lives/2022/12/11/anaelle-martin/"
to = "/lives/2023-02-06-anaelle-martin/"

[[redirects]]
from = "/actualites/archives/"
to = "/lives/archives/"

[[redirects]]
from = "/fr/"
to = "/"

[[redirects]]
from = "/actualites/"
to = "/lives/"

